apiVersion: v1
kind: PersistentVolume

metadata:
  name: task-manager-pv

spec:
  storageClassName: manual

  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /tmp/task-manager-data
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /tmp/task-manager-data